<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();
        DB::table('students')->insert(
            array(
                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],

                ['reg_no'=> 'F'. $faker->unique()->numerify('#########'),
                'index_no'=> $faker->unique()->numerify('##########'),
                'title'=> $faker->title(),
                'first_name'=> $faker->firstName,
                'last_name'=> $faker->lastName,
                'gender'=>$faker->randomElement($array = array ('male', 'female')) ,
                'nic'=>$faker->unique()->numerify('#########').'V',
                'email'=>$faker->email,
                'citizenship'=>'Sri Lankan',
                'dob'=>$faker->dateTimeBetween('1980-01-01', '2000-12-31'),
                'birth_cert'=>'0',
                'nic_img'=>'0',
                'created_at'=>$faker->dateTimeBetween('2020-11-01', '2020-11-30'),
                'updated_at'=> '2020-11-30 13:14:56'],



            )
        );
    }
}
